In [1]:
import numpy as np

In [13]:
onesArray = np.diag([1,2,3])


In [14]:
onesArray


array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## Slicing of the numpy array

In [53]:
# First Row
onesArray[:, 0]

array([1, 0, 0])

In [54]:
# second Row
onesArray[:, 1]

array([0, 2, 0])

In [55]:
#Third Row
onesArray[:, 2]

array([0, 0, 3])

In [58]:
# First Column
onesArray[:, 0:1]

array([[1],
       [0],
       [0]])

In [59]:
# Second column
onesArray[:, 1:2]

array([[0],
       [2],
       [0]])

In [61]:
# Third Column
onesArray[:, 2:3]

array([[0],
       [0],
       [3]])

array([[1, 0, 0]])

array([[1, 0, 0]])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

array([[0, 0],
       [2, 0],
       [0, 3]])

array([[0],
       [0],
       [3]])

In [33]:
onesArray[:, :1

array([[1],
       [0],
       [0]])

In [34]:
onesArray[:, :2]

array([[1, 0],
       [0, 2],
       [0, 0]])

In [36]:
onesArray[:, 1:2]

array([[0],
       [2],
       [0]])

In [37]:
onesArray[:, 2:3]

array([[0],
       [0],
       [3]])

In [35]:
onesArray[:, :3]

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])